# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:CiwD5/jAWzLAATTWgRmOz65M,iv:BAORKnVuBYwkM5sRPcARk0S2IxgZCAB9IWGwHjGH5RQ=,tag:EcmdPtpJPTjWl+T50g7Y0g==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:zqJZ8v7/nb9n/J1j27aa3+dLHhTT6dfhKg==,iv:Fl+iE85FenrRXoyfIQs8sRYZPzbn8+Dx+RPyVCU3i0o=,tag:wwU5jFrI3LXAvzp3sbRH3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zca92p6etudda8qn2ncgt7rnajxzuwd8pdwgh6gqe52dyxvnmu7s28psf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VjhYNWJRYnkrTnIzYzRv
            OEFiK25YbUFJYks3Rk9FbnN6VzRmcUhJRmhJCmE3N05WZjB0OUdpLy9mQ2pkZWE3
            eTFBNVkyQ1ozd2lnZThpOW9zYWRlN1kKLS0tIDd4RjJOSW1yYkhnQUVseThBR09F
            ZW9RVER1d2pwWVlBT01uS28rM2tyMFUKiQpX2NEahXf/8+F/OdaytJteAai10zQH
            lcaRtf+7AHH8+B6+cv7TwtoSFqxi/cF3xG0AHZSIYC0fhExp/jvZJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-27T22:07:29Z"
    mac: ENC[AES256_GCM,data:WZZ6liKBXrKZRupYxpnAqyTtGft+lcLR18euWH6txUO3S5wLlf9Anp1K0vjopb1s33jMeKHD3Av9je56LCLi3u2fUBpLvHH0cI6sQeISnaUy5/Wrw/1gti6wBHZueEw8V3kWvv1ihOreA9ySYIcnApPwkZ7C6AxJaqDFtT7r4qI=,iv:hvo6WsnUGh9QTVEneGvcB1KuZZI2y5qNa4ce/f02UZU=,tag:Txyx0AGxK+vTKke8vUpYsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
