---
- name: Add user to sudoers
  lineinfile:
    path: "/etc/sudoers.d/{{ ansible_user }}_nopasswd"
    line: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD:ALL"
    state: present
    mode: "0440"
    create: yes
    validate: 'visudo -cf %s'

- name: Add additional user SSH public keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop: "{{ ssh_authorized_keys }}"
  when:
    - ssh_authorized_keys is defined
    - ssh_authorized_keys is iterable
    - ssh_authorized_keys | length > 0
