# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:nfKDMhy40nIp8lxJDAQU/bg2R/CKL7wK6+UkuVAjvp3GwrbnKA==,iv:8wvWoLx7L9VDFNima/5hhaDwktm9v3rnYRBxYTCo7Bw=,tag:yl9tisMeZ00fAM1DkCdA7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zca92p6etudda8qn2ncgt7rnajxzuwd8pdwgh6gqe52dyxvnmu7s28psf2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N0VsN3g2Y0E5SUx4Vkov
            SlpjSzQ2R2V3TjR6WUZLREJ0aTNxdEdMTVJZCkxIa0RHRko0QUFEWUZjcm80OUly
            V1NlSjZWOUl5eE5jcGhzWkFtbVM2QmcKLS0tIC9aNk1ZU1YwaWFCRVVCNk1vWThH
            Smd2TUIzMlJoOW82ME14cTExK3l3NkUKSte2+4SZ+pX5iIfK9tA8qdsZCFSEqJeX
            QdkLXA1+OEwYzIzwE7YxrBzdxy2p29JhWsFDP288hLb2x3eHAzkiMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-27T22:07:29Z"
    mac: ENC[AES256_GCM,data:CXeu21wmNX1GPwTw8afnRz0DQIn5x9htfD/lKz4HwPzfOO5WaQJSJQR/P6eTvQm6nW0Rk5ztzzFpWZ1CCZEk4HZJmiJs2N3ee+mpmCFdgOJ9VLoqjq/Xbwhu1GAVJw/pOJ1A0MwHORgxC72JMlJ3+3Txn95b9yOKZAjS790cczY=,iv:w0aI2Pq2lru8/rpeUfE6jmfXvrHaN6AUOC3yMHPhGuo=,tag:f+pAZNBRoSHsQwEw0ZN+3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
